name: Build Go App
description: "Builds and zips the Poetry app for uploading to AWS Lambda"

inputs:

  app-name:
    description: "Name of the app"
    required: true

  poetry-version:
    description: "Version of poetry to use"
    required: false
    default: ""

  pak-name:
    description: "Contributing package name"
    required: false
    default: ""

runs:
  using: "composite"

  steps:

    - shell: bash
      run: |
        POETRY_VERSION=$([ -z ${{ inputs.poetry-version }} ] || echo "==${{ inputs.poetry-version }}")
        PAK_NAME=$([ -z ${{ inputs.pak-name }} ] && echo ${{ inputs.app-name }} || echo ${{ inputs.pak-name }})

        pip -q install poetry$POETRY_VERSION
        poetry export -f requirements.txt --output requirements.txt
        pip -q install -r requirements.txt -t ./$PAK_NAME
        cd ./$PAK_NAME && zip -q -r9 ../${{ inputs.app-name }}.zip * -x "bin/*"
