name: Terraform
description: "Execute terraform init, validate, plan, and apply"

inputs:

  working-dir:
    description: "'Terraform init' working directory"
    required: false
    default: terraform

  backend-config-file:
    description: "'Terraform init' backend config file location"
    required: false
    default: ""

  backend-configs:
    description: "'Terraform init' backend config parameters"
    required: false
    default: ""

  plan-file:
    description: "'Terraform plan' output filename"
    required: false
    default: plan.tfout

  var-file:
    description: "'Terraform plan' tfvars file location"
    required: false
    default: ""

  vars:
    description: "'Terraform plan' CLI variables"
    required: false
    default: ""

  destroy:
    description: "'Terraform apply' destroy flag"
    required: false
    default: "false"

runs:
  using: "composite"

  steps:

    - shell: bash
      run: |
        cd ${{ inputs.working-dir }}

        if [ -z "${{ inputs.backend-configs }}" ]
        then
          backend_config=$([ -z "${{ inputs.backend-config-file }}" ] || echo "-backend-config=${{ inputs.backend-config-file }}")
        else
          for config in ${{ inputs.backend-configs }}
          do
            IFS='='
            read -ra ADDR <<< "$config"
            IFS=' '
            echo "${ADDR[0]} = \"${ADDR[1]}\"" >> init.config
          done
          backend_config="-backend-config=init.config"
        fi

        echo "TODO : same removal of '-vars ' for vars as was done for backend"
        var_file=$([ -z "${{ inputs.var-file }}" ] || echo "-var-file=${{ inputs.var-file }}")

        terraform init -no-color -input=false "$backend_config"
        terraform validate

        if [ ${{ inputs.destroy }} == "true" ]
        then
          terraform apply -destroy -lock-timeout=120s -input=false -auto-approve $var_file ${{ inputs.vars }}
        else
          terraform plan -lock-timeout=60s -out=.terraform/${{ inputs.plan-file }} $var_file ${{ inputs.vars }}
          terraform apply -lock-timeout=120s -input=false -auto-approve .terraform/${{ inputs.plan-file }}
        fi
