name: Run Pytest Via Poetry
description: "Run Pytest via Poetry"

inputs:

  poetry-version:
    description: "Version of poetry to use"
    required: false
    default: ""

runs:
  using: "composite"

  steps:

    - shell: bash
      run: |
        POETRY_VERSION=$([ -z ${{ inputs.poetry-version }} ] || echo "==${{ inputs.poetry-version }}")

        pip install poetry$POETRY_VERSION
        poetry install
        poetry run pytest -v
